/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScrapeRouteImport } from './routes/api/scrape'
import { Route as ApiEmbeddingsRouteImport } from './routes/api/embeddings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCompetitorsRouteImport } from './routes/_app.competitors'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppAboutRouteImport } from './routes/_app.about'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeRoute = ApiScrapeRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbeddingsRoute = ApiEmbeddingsRouteImport.update({
  id: '/api/embeddings',
  path: '/api/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/assistant': typeof AppAssistantRoute
  '/competitors': typeof AppCompetitorsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/assistant': typeof AppAssistantRoute
  '/competitors': typeof AppCompetitorsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assistant'
    | '/competitors'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/competitors'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/about'
    | '/_app/assistant'
    | '/_app/competitors'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmbeddingsRoute: typeof ApiEmbeddingsRoute
  ApiScrapeRoute: typeof ApiScrapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embeddings': {
      id: '/api/embeddings'
      path: '/api/embeddings'
      fullPath: '/api/embeddings'
      preLoaderRoute: typeof ApiEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmbeddingsRoute: ApiEmbeddingsRoute,
  ApiScrapeRoute: ApiScrapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
