/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiScrapeRouteImport } from './routes/api/scrape'
import { Route as ApiEmbeddingsRouteImport } from './routes/api/embeddings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCompetitorsRouteImport } from './routes/_app.competitors'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as ApiVoiceSttRouteImport } from './routes/api/voice/stt'
import { Route as ApiCompetitorsValidateSeedsRouteImport } from './routes/api/competitors/validate-seeds'
import { Route as ApiCompetitorsScrapeRouteImport } from './routes/api/competitors/scrape'
import { Route as ApiCompetitorsListRouteImport } from './routes/api/competitors/list'
import { Route as ApiCompetitorsDiscoverRouteImport } from './routes/api/competitors/discover'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeRoute = ApiScrapeRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbeddingsRoute = ApiEmbeddingsRouteImport.update({
  id: '/api/embeddings',
  path: '/api/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const ApiVoiceSttRoute = ApiVoiceSttRouteImport.update({
  id: '/api/voice/stt',
  path: '/api/voice/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsValidateSeedsRoute =
  ApiCompetitorsValidateSeedsRouteImport.update({
    id: '/api/competitors/validate-seeds',
    path: '/api/competitors/validate-seeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCompetitorsScrapeRoute = ApiCompetitorsScrapeRouteImport.update({
  id: '/api/competitors/scrape',
  path: '/api/competitors/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsListRoute = ApiCompetitorsListRouteImport.update({
  id: '/api/competitors/list',
  path: '/api/competitors/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsDiscoverRoute = ApiCompetitorsDiscoverRouteImport.update({
  id: '/api/competitors/discover',
  path: '/api/competitors/discover',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/about': typeof AppAboutRoute
  '/assistant': typeof AppAssistantRoute
  '/competitors': typeof AppCompetitorsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/profile': typeof AppProfileRoute
  '/upload': typeof AppUploadRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/competitors/discover': typeof ApiCompetitorsDiscoverRoute
  '/api/competitors/list': typeof ApiCompetitorsListRoute
  '/api/competitors/scrape': typeof ApiCompetitorsScrapeRoute
  '/api/competitors/validate-seeds': typeof ApiCompetitorsValidateSeedsRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/about': typeof AppAboutRoute
  '/assistant': typeof AppAssistantRoute
  '/competitors': typeof AppCompetitorsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/profile': typeof AppProfileRoute
  '/upload': typeof AppUploadRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/competitors/discover': typeof ApiCompetitorsDiscoverRoute
  '/api/competitors/list': typeof ApiCompetitorsListRoute
  '/api/competitors/scrape': typeof ApiCompetitorsScrapeRoute
  '/api/competitors/validate-seeds': typeof ApiCompetitorsValidateSeedsRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/upload': typeof AppUploadRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/competitors/discover': typeof ApiCompetitorsDiscoverRoute
  '/api/competitors/list': typeof ApiCompetitorsListRoute
  '/api/competitors/scrape': typeof ApiCompetitorsScrapeRoute
  '/api/competitors/validate-seeds': typeof ApiCompetitorsValidateSeedsRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/about'
    | '/assistant'
    | '/competitors'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/profile'
    | '/upload'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
    | '/api/search'
    | '/api/upload'
    | '/api/competitors/discover'
    | '/api/competitors/list'
    | '/api/competitors/scrape'
    | '/api/competitors/validate-seeds'
    | '/api/voice/stt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/about'
    | '/assistant'
    | '/competitors'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/profile'
    | '/upload'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
    | '/api/search'
    | '/api/upload'
    | '/api/competitors/discover'
    | '/api/competitors/list'
    | '/api/competitors/scrape'
    | '/api/competitors/validate-seeds'
    | '/api/voice/stt'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/about'
    | '/_app/assistant'
    | '/_app/competitors'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/profile'
    | '/_app/upload'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
    | '/api/search'
    | '/api/upload'
    | '/api/competitors/discover'
    | '/api/competitors/list'
    | '/api/competitors/scrape'
    | '/api/competitors/validate-seeds'
    | '/api/voice/stt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmbeddingsRoute: typeof ApiEmbeddingsRoute
  ApiScrapeRoute: typeof ApiScrapeRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiCompetitorsDiscoverRoute: typeof ApiCompetitorsDiscoverRoute
  ApiCompetitorsListRoute: typeof ApiCompetitorsListRoute
  ApiCompetitorsScrapeRoute: typeof ApiCompetitorsScrapeRoute
  ApiCompetitorsValidateSeedsRoute: typeof ApiCompetitorsValidateSeedsRoute
  ApiVoiceSttRoute: typeof ApiVoiceSttRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embeddings': {
      id: '/api/embeddings'
      path: '/api/embeddings'
      fullPath: '/api/embeddings'
      preLoaderRoute: typeof ApiEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/voice/stt': {
      id: '/api/voice/stt'
      path: '/api/voice/stt'
      fullPath: '/api/voice/stt'
      preLoaderRoute: typeof ApiVoiceSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/validate-seeds': {
      id: '/api/competitors/validate-seeds'
      path: '/api/competitors/validate-seeds'
      fullPath: '/api/competitors/validate-seeds'
      preLoaderRoute: typeof ApiCompetitorsValidateSeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/scrape': {
      id: '/api/competitors/scrape'
      path: '/api/competitors/scrape'
      fullPath: '/api/competitors/scrape'
      preLoaderRoute: typeof ApiCompetitorsScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/list': {
      id: '/api/competitors/list'
      path: '/api/competitors/list'
      fullPath: '/api/competitors/list'
      preLoaderRoute: typeof ApiCompetitorsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/discover': {
      id: '/api/competitors/discover'
      path: '/api/competitors/discover'
      fullPath: '/api/competitors/discover'
      preLoaderRoute: typeof ApiCompetitorsDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmbeddingsRoute: ApiEmbeddingsRoute,
  ApiScrapeRoute: ApiScrapeRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiCompetitorsDiscoverRoute: ApiCompetitorsDiscoverRoute,
  ApiCompetitorsListRoute: ApiCompetitorsListRoute,
  ApiCompetitorsScrapeRoute: ApiCompetitorsScrapeRoute,
  ApiCompetitorsValidateSeedsRoute: ApiCompetitorsValidateSeedsRoute,
  ApiVoiceSttRoute: ApiVoiceSttRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
