/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiScrapeRouteImport } from './routes/api/scrape'
import { Route as ApiEmbeddingsRouteImport } from './routes/api/embeddings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppIntelligenceRouteImport } from './routes/_app.intelligence'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCompetitorsRouteImport } from './routes/_app.competitors'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as ApiVoiceTtsRouteImport } from './routes/api/voice/tts'
import { Route as ApiVoiceSttRouteImport } from './routes/api/voice/stt'
import { Route as ApiScanExtractRouteImport } from './routes/api/scan/extract'
import { Route as ApiScanCommitRouteImport } from './routes/api/scan/commit'
import { Route as ApiCompetitorsValidateSeedsRouteImport } from './routes/api/competitors/validate-seeds'
import { Route as ApiCompetitorsScrapeRouteImport } from './routes/api/competitors/scrape'
import { Route as ApiCompetitorsListRouteImport } from './routes/api/competitors/list'
import { Route as ApiCompetitorsDiscoverRouteImport } from './routes/api/competitors/discover'
import { Route as ApiCompetitorsAnalyzeRouteImport } from './routes/api/competitors/analyze'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeRoute = ApiScrapeRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbeddingsRoute = ApiEmbeddingsRouteImport.update({
  id: '/api/embeddings',
  path: '/api/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const ApiVoiceTtsRoute = ApiVoiceTtsRouteImport.update({
  id: '/api/voice/tts',
  path: '/api/voice/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSttRoute = ApiVoiceSttRouteImport.update({
  id: '/api/voice/stt',
  path: '/api/voice/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanExtractRoute = ApiScanExtractRouteImport.update({
  id: '/api/scan/extract',
  path: '/api/scan/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanCommitRoute = ApiScanCommitRouteImport.update({
  id: '/api/scan/commit',
  path: '/api/scan/commit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsValidateSeedsRoute =
  ApiCompetitorsValidateSeedsRouteImport.update({
    id: '/api/competitors/validate-seeds',
    path: '/api/competitors/validate-seeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCompetitorsScrapeRoute = ApiCompetitorsScrapeRouteImport.update({
  id: '/api/competitors/scrape',
  path: '/api/competitors/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsListRoute = ApiCompetitorsListRouteImport.update({
  id: '/api/competitors/list',
  path: '/api/competitors/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsDiscoverRoute = ApiCompetitorsDiscoverRouteImport.update({
  id: '/api/competitors/discover',
  path: '/api/competitors/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsAnalyzeRoute = ApiCompetitorsAnalyzeRouteImport.update({
  id: '/api/competitors/analyze',
  path: '/api/competitors/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/about': typeof AppAboutRoute
  '/assistant': typeof AppAssistantRoute
  '/billing': typeof AppBillingRoute
  '/competitors': typeof AppCompetitorsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/inventory': typeof AppInventoryRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/upload': typeof AppUploadRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/competitors/analyze': typeof ApiCompetitorsAnalyzeRoute
  '/api/competitors/discover': typeof ApiCompetitorsDiscoverRoute
  '/api/competitors/list': typeof ApiCompetitorsListRoute
  '/api/competitors/scrape': typeof ApiCompetitorsScrapeRoute
  '/api/competitors/validate-seeds': typeof ApiCompetitorsValidateSeedsRoute
  '/api/scan/commit': typeof ApiScanCommitRoute
  '/api/scan/extract': typeof ApiScanExtractRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/about': typeof AppAboutRoute
  '/assistant': typeof AppAssistantRoute
  '/billing': typeof AppBillingRoute
  '/competitors': typeof AppCompetitorsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/inventory': typeof AppInventoryRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/upload': typeof AppUploadRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/competitors/analyze': typeof ApiCompetitorsAnalyzeRoute
  '/api/competitors/discover': typeof ApiCompetitorsDiscoverRoute
  '/api/competitors/list': typeof ApiCompetitorsListRoute
  '/api/competitors/scrape': typeof ApiCompetitorsScrapeRoute
  '/api/competitors/validate-seeds': typeof ApiCompetitorsValidateSeedsRoute
  '/api/scan/commit': typeof ApiScanCommitRoute
  '/api/scan/extract': typeof ApiScanExtractRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/intelligence': typeof AppIntelligenceRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/upload': typeof AppUploadRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embeddings': typeof ApiEmbeddingsRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/competitors/analyze': typeof ApiCompetitorsAnalyzeRoute
  '/api/competitors/discover': typeof ApiCompetitorsDiscoverRoute
  '/api/competitors/list': typeof ApiCompetitorsListRoute
  '/api/competitors/scrape': typeof ApiCompetitorsScrapeRoute
  '/api/competitors/validate-seeds': typeof ApiCompetitorsValidateSeedsRoute
  '/api/scan/commit': typeof ApiScanCommitRoute
  '/api/scan/extract': typeof ApiScanExtractRoute
  '/api/voice/stt': typeof ApiVoiceSttRoute
  '/api/voice/tts': typeof ApiVoiceTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/about'
    | '/assistant'
    | '/billing'
    | '/competitors'
    | '/customers'
    | '/dashboard'
    | '/integrations'
    | '/intelligence'
    | '/inventory'
    | '/privacy'
    | '/profile'
    | '/scan'
    | '/upload'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
    | '/api/search'
    | '/api/upload'
    | '/api/competitors/analyze'
    | '/api/competitors/discover'
    | '/api/competitors/list'
    | '/api/competitors/scrape'
    | '/api/competitors/validate-seeds'
    | '/api/scan/commit'
    | '/api/scan/extract'
    | '/api/voice/stt'
    | '/api/voice/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/about'
    | '/assistant'
    | '/billing'
    | '/competitors'
    | '/customers'
    | '/dashboard'
    | '/integrations'
    | '/intelligence'
    | '/inventory'
    | '/privacy'
    | '/profile'
    | '/scan'
    | '/upload'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
    | '/api/search'
    | '/api/upload'
    | '/api/competitors/analyze'
    | '/api/competitors/discover'
    | '/api/competitors/list'
    | '/api/competitors/scrape'
    | '/api/competitors/validate-seeds'
    | '/api/scan/commit'
    | '/api/scan/extract'
    | '/api/voice/stt'
    | '/api/voice/tts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/_app/about'
    | '/_app/assistant'
    | '/_app/billing'
    | '/_app/competitors'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/integrations'
    | '/_app/intelligence'
    | '/_app/inventory'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/scan'
    | '/_app/upload'
    | '/api/analytics'
    | '/api/chat'
    | '/api/embeddings'
    | '/api/scrape'
    | '/api/search'
    | '/api/upload'
    | '/api/competitors/analyze'
    | '/api/competitors/discover'
    | '/api/competitors/list'
    | '/api/competitors/scrape'
    | '/api/competitors/validate-seeds'
    | '/api/scan/commit'
    | '/api/scan/extract'
    | '/api/voice/stt'
    | '/api/voice/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmbeddingsRoute: typeof ApiEmbeddingsRoute
  ApiScrapeRoute: typeof ApiScrapeRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiCompetitorsAnalyzeRoute: typeof ApiCompetitorsAnalyzeRoute
  ApiCompetitorsDiscoverRoute: typeof ApiCompetitorsDiscoverRoute
  ApiCompetitorsListRoute: typeof ApiCompetitorsListRoute
  ApiCompetitorsScrapeRoute: typeof ApiCompetitorsScrapeRoute
  ApiCompetitorsValidateSeedsRoute: typeof ApiCompetitorsValidateSeedsRoute
  ApiScanCommitRoute: typeof ApiScanCommitRoute
  ApiScanExtractRoute: typeof ApiScanExtractRoute
  ApiVoiceSttRoute: typeof ApiVoiceSttRoute
  ApiVoiceTtsRoute: typeof ApiVoiceTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embeddings': {
      id: '/api/embeddings'
      path: '/api/embeddings'
      fullPath: '/api/embeddings'
      preLoaderRoute: typeof ApiEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence': {
      id: '/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/voice/tts': {
      id: '/api/voice/tts'
      path: '/api/voice/tts'
      fullPath: '/api/voice/tts'
      preLoaderRoute: typeof ApiVoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/stt': {
      id: '/api/voice/stt'
      path: '/api/voice/stt'
      fullPath: '/api/voice/stt'
      preLoaderRoute: typeof ApiVoiceSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/extract': {
      id: '/api/scan/extract'
      path: '/api/scan/extract'
      fullPath: '/api/scan/extract'
      preLoaderRoute: typeof ApiScanExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/commit': {
      id: '/api/scan/commit'
      path: '/api/scan/commit'
      fullPath: '/api/scan/commit'
      preLoaderRoute: typeof ApiScanCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/validate-seeds': {
      id: '/api/competitors/validate-seeds'
      path: '/api/competitors/validate-seeds'
      fullPath: '/api/competitors/validate-seeds'
      preLoaderRoute: typeof ApiCompetitorsValidateSeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/scrape': {
      id: '/api/competitors/scrape'
      path: '/api/competitors/scrape'
      fullPath: '/api/competitors/scrape'
      preLoaderRoute: typeof ApiCompetitorsScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/list': {
      id: '/api/competitors/list'
      path: '/api/competitors/list'
      fullPath: '/api/competitors/list'
      preLoaderRoute: typeof ApiCompetitorsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/discover': {
      id: '/api/competitors/discover'
      path: '/api/competitors/discover'
      fullPath: '/api/competitors/discover'
      preLoaderRoute: typeof ApiCompetitorsDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors/analyze': {
      id: '/api/competitors/analyze'
      path: '/api/competitors/analyze'
      fullPath: '/api/competitors/analyze'
      preLoaderRoute: typeof ApiCompetitorsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScanRoute: typeof AppScanRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppBillingRoute: AppBillingRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppScanRoute: AppScanRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmbeddingsRoute: ApiEmbeddingsRoute,
  ApiScrapeRoute: ApiScrapeRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiCompetitorsAnalyzeRoute: ApiCompetitorsAnalyzeRoute,
  ApiCompetitorsDiscoverRoute: ApiCompetitorsDiscoverRoute,
  ApiCompetitorsListRoute: ApiCompetitorsListRoute,
  ApiCompetitorsScrapeRoute: ApiCompetitorsScrapeRoute,
  ApiCompetitorsValidateSeedsRoute: ApiCompetitorsValidateSeedsRoute,
  ApiScanCommitRoute: ApiScanCommitRoute,
  ApiScanExtractRoute: ApiScanExtractRoute,
  ApiVoiceSttRoute: ApiVoiceSttRoute,
  ApiVoiceTtsRoute: ApiVoiceTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
